name: Security Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install security tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gitleaks trufflehog semgrep syft grype bandit
          pip install safety
      - name: Install additional security tools
        run: |
          pip install checkov
          sudo apt-get install -y dependency-check
      - name: Install hadolint
        run: |
          wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint
      - name: Run security scan
        run: |
          python main.py
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/
      - name: Notify on critical issues
        if: always()
        run: |
          if grep -q 'CRITICAL' reports/*.json; then
            echo "Critical issues found! Sending notification..."
            # Add your notification logic here (e.g., email, Slack)
          fi
